# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install packages
      - name: Install Packages
        run: yarn install

      # Runs a single command using the runners shell
      - name: Create Cron Job
        run: node create-cron-job.js

      - name: Check files
        run: ls -all
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: prakash
          author_email: prakash106kumar@gmail.com
          message: 'new cron job'
          add: '*.yml'
